[package]
name = "cddl-lib"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cbor_event = "2.1.3"
wasm-bindgen = { version = "0.2", features=["serde-serialize"] }
